### ISSUE TITLE
HashiCorp Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [SumoLogic/terraform-provider-sumologic#102]
Hey Team,
My name is Chris Griggs and I am the HashiCorp Partner SE for Terraform and work with you to certify this integration. I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the develop branch at git commit  [2ad5cf3](https://github.com/SumoLogic/sumologic-terraform-provider/commit/2ad5cf388c1786bb9c2c7a7b5cbf03e0a42a8937) 

- [x] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in all 100+ TF providers. 

- [x] There is a standard [GNUmakefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile)which is has all the necessary make targets that are used in our testing, build and release processes. You will need to swap you make file out for the standard on linked above. 

- [x] Along with the GNUmakefile there are a few bash scripts that are used to build and release the provider. Can can simply copy over the scripts from GitHub provider repo [here](https://github.com/terraform-providers/terraform-provider-github/tree/master/scripts)

- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] All official Terraform provider use a [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/) within each repo, you’ll need remove the Apache license and add this [LICENSE](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/LICENSE) file to this repository.

- [x] One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] You will need to build  the formatting for the website documentation in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for each resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 
     The Terraform.io website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy the website locally follow the steps outlined in the README.
	- Once you've synced the current submodules there are 3 more steps required for adding you provider
	- Add the PROVIDER provider as a submodule to the terraform-website/ directory with: `git submodule add -b master https://github.com/REPO/terraform-provider-PROVIDER ext/providers/PROVIDER`
	- Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run: `ln -s ../../../../ext/providers/PROVIDER/website/docs PROVIDER`
	- And then change to the working directory to "terraform-website/content/source/layouts/" to run: `ln -s ../../../ext/providers/PROVIDER/website/PROVIDER.erb`
	- After those additions, you can then run the "make website" target to spin up the website using Docker desktop. 

- [ ] I wasnt able to find a confirmation email for the provider testing account at terraform-acctest@hashicorp.com account. Could you resend?

Let me know if you have any questions. 
Best,
Chris

**Comment by cgriggs01** [comment]
Hi Team, 

The changes look great, I just have one more item to address before moving on to the migration and release process.  Could you change the name of this repository to the standard format `terraform-provider-sumologic`?  This is used for all Terraform providers. 

I am ready to start the final phase of the partner provider program will go as follows:
- A repository under the same name `terraform-providers-sumologic` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- Your provider code will be pushed up to the new repository
- The binaries during release are pulled from the master branch. 
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The first release will be tagged `2.0.0` per the CHANGELOG.md
- You and whomever else on your team will be granted “write” access over the new repository are you are still seen as the owners and maintainers of the provider, before I grant you access, you’ll must review and agree to our community guidelines, which I’ll include below. 
- Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

Let me know that you're ready to begin the final process. We look forward to releasing this integration with you.

**Comment by seansain** [comment]
Thanks @cgriggs01 for reviewing! Just finished the last two steps so we should be ready.

**Comment by cgriggs01** [comment]
Hi @seansain,

Thanks for participation in the Terraform Provider development program. We've completed the migration and first release of the Terraform provider for SumoLogic. 

The provider binary can be found at: releases.hashicorp.com/
Website documentation is now live at: terraform.io/docs/providers/sumologic/index.html

Let me know if you have any questions. I'll close this issue now.

**Comment by seansain** [comment]
Thanks @cgriggs01
What does the process going forward look like? How should we continue contributing and improving upon our provider and make sure all releases are stable?

**Comment by cgriggs01** [comment]
@seansain, Could you email at cgriggs@hashicorp.com and we can follow up there.
