### ISSUE TITLE
Feature request - ability to manage Admin Recommended content

### ISSUE THREAD

**Issue by mccartney** [SumoLogic/terraform-provider-sumologic#115]
I'd be great to be able to mark some content as Admin Recommended in Terraform using this feature: https://help.sumologic.com/Manage/Content_Sharing/Content_Sharing_FAQ#i-want-to-create-a-hierarchy-of-folders-for-my-company-so-that-e

**Comment by mccartney** [comment]
Related to #215 #211

**Comment by sumovishal** [comment]
@mccartney this should be resolved now? We have AdminRecommended data source now.

**Comment by mccartney** [comment]
Related to #322
