### ISSUE TITLE
Feature request - it should be possible to import a scheduled view

### ISSUE THREAD

**Issue by mccartney** [SumoLogic/terraform-provider-sumologic#133]

**Comment by sakshi-sumo** [comment]
@mccartney @seansain https://github.com/SumoLogic/terraform-provider-sumologic/pull/126/files - would a similar change work for this? And how can I test it?

**Comment by sakshi-sumo** [comment]
@mccartney - https://sumologic.slack.com/archives/CB98VPJCT/p1610039819180500?thread_ts=1609923038.160200&cid=CB98VPJCT I saw this. Except the formatting issues with queries, were there other challenges in implementing this?
And how does import work ? How will one import (one id) get mapped to resources in multiple orgs?

**Comment by mccartney** [comment]
> https://github.com/SumoLogic/terraform-provider-sumologic/pull/126/files - would a similar change work for this? And how can I test it?

Most likely it would work.
Testing it:
- You can build the local version of the Terraform provider (without it being published and/or released)
- I'd create a simple Scheduled View in UI (manually)
- Write a `.tf` file with the same definition
- `terraform plan` should offer you to create the view (which you wouldn't want)
- And then try `terraform import`
- next run of `terraform plan` should not offer you to create or alter the scheduled view in any way

**Comment by mccartney** [comment]
Fixed in #152
