### ISSUE TITLE
Feature Request: Dashboards (New)

### ISSUE THREAD

**Issue by cbuto** [SumoLogic/terraform-provider-sumologic#138]
It would be awesome to have support for creating [Dashboards](https://help.sumologic.com/Visualizations-and-Alerts/Dashboard_(New))!

**Comment by ccog** [comment]
@cbuto dashboards are supported--you can check out the [Content API](https://api.sumologic.com/docs/#operation/beginAsyncImport) for some details (select the `DashboardSyncDefinition` type). As with other content types though, I'm finding the best approach is to create content in the GUI, then export it into a terraform resource config.

**Comment by cbuto** [comment]
thanks @ccog, I wasn't sure if dashboards were supported via `sumologic_content`. I will give that a shot!

**Comment by sumovishal** [comment]
@cbuto, @ccog the latest version (https://github.com/SumoLogic/terraform-provider-sumologic/releases/tag/v2.8.0.) supports New Dashboards. You might want to use the new resource `sumologic_dashboard` instead of `sumologic_content`.
