### ISSUE TITLE
Sumologic_user's is_active property is not documented and behaves in a confusing manner

### ISSUE THREAD

**Issue by fishfacemcgee** [SumoLogic/terraform-provider-sumologic#140]
In https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/website/docs/r/user.html.markdown, a property for the user is labeled as `active`. However, in the code for the resource, there's [only one called `is_active`](https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/sumologic/resource_sumologic_user.go#L51). Presumably, the code is the source of truth here. However, it also appears to not behave correctly for an optional value. The documentation says that it defaults to true, but if it's not explicitly set, future `terraform plan`s attempt to set it to null, causing an incorrectly dirty state.

```
~ resource "sumologic_user" "redacted" {
        email      = "redacted@redacted.com"
        first_name = "redacted"
        id         = "redacted"
      - is_active  = true -> null
        last_name  = "redacted"
        role_ids   = [
            "redacted",
        ]
    }
```

**Comment by seansain** [comment]
Thanks for pointing this out. Going to make `is_active` required to coordinate with the API. #142
