### ISSUE TITLE
Update documentation with support for terraform 0.13

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/terraform-provider-sumologic#141]
Since [PRs are already built with terraform 0.13](https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/.github/workflows/test.yml#L57) let's update [README's requirements section](https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/README.md#requirements) to reflect that.

**Comment by seansain** [comment]
sure, I'll get that updated

**Comment by seansain** [comment]
https://github.com/SumoLogic/terraform-provider-sumologic/commit/8d99fc2f0737b317ee8c343b78937d49f6feb106
