### ISSUE TITLE
sumologic_role data source fails with a space in the role name

### ISSUE THREAD

**Issue by cmartin-twilio** [SumoLogic/terraform-provider-sumologic#158]
When using the sumologic_role data source to import a role with a space in the name fails when running terraform plan.  Using the following data definition:

```
data "sumologic_role" "example_role" {
  name = "Test Role"
}
```

will fail with the following error

```
data.sumologic_role.seceng_role: Refreshing state...

Error: role with name Test Role not found: <h1>Bad Message 400</h1><pre>reason: Illegal character SPACE=' '</pre>

  on main.tf line 1, in data "sumologic_role" "example_role":
   1: data "sumologic_role" "example_role" {
```

A workaround for this issue is to encode the space in the role name with url encoding.

**Comment by seansain** [comment]
Thanks for filing. Will include in the next release. If you are using this workaround and update to 2.9.1 or beyond please remove the spaces from your role name.
