### ISSUE TITLE
2.7.1 does not like the Sumo default partitions

### ISSUE THREAD

**Issue by upstart-swiss** [SumoLogic/terraform-provider-sumologic#159]
```
resource "sumologic_partition" "sumologic_volume" {
  name               = "sumologic_volume"
  analytics_tier     = "continuous"
  routing_expression = ""
  retention_period   = 630
  is_compliant       = false
}
```
Triggers:
`Error: expected length of routing_expression to be in the range (1 - 16384), got `

This wants a routing expression, and adding one would cause problems. Same for things like the default partition.
How can I properly manage this?

**Comment by seansain** [comment]
Thanks! Will get this fixed asap!
