### ISSUE TITLE
Error verifying GPG signature for provider "sumologic"

### ISSUE THREAD

**Issue by EdisonHEXUAN** [SumoLogic/terraform-provider-sumologic#187]
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.

**Comment by EdisonHEXUAN** [comment]
provider "sumologic" {
  version = "~> 2.9"
}

**Comment by sumovishal** [comment]
Works for me. 
```
Initializing the backend...

Initializing provider plugins...
- Finding sumologic/sumologic versions matching "~> 2.9"...
- Installing sumologic/sumologic v2.9.3...
- Installed sumologic/sumologic v2.9.3 (signed by a HashiCorp partner, key ID 58C1F2777F8E2367)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
```

Can you paste the entire log?

**Comment by EdisonHEXUAN** [comment]
![image](https://user-images.githubusercontent.com/34933673/116353031-af693d00-a828-11eb-90c8-8eec8a6eadda.png)

Terraform Version: v0.12.26

**Comment by denis-matchenko** [comment]
Hello, get a very similar error too.
![image](https://user-images.githubusercontent.com/70911436/116412769-ac2d7b80-a83f-11eb-9178-b2c86951d080.png)

Terraform Version: v0.11.13

**Comment by aclarknexient** [comment]
We are also seeing the same error. It's blocking several deployments because we are unable to trust the plugin until we hear from Sumologic developers regarding whether or not the repo has been compromised.

**Comment by sumovishal** [comment]
We are looking into it. AFIAK, we haven't changed the key. We did a new release yesterday. That might have triggered something. Let me try to reproduce the issue locally. FWIW, I am on terraform version `v0.14.5` and it works for me.

**Comment by sumovishal** [comment]
Looks like there was a security incident where HashiCorp's private key were compromised. See https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512. They rotated the release signing key (more details here https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570).

I was able to reproduce the issue with Terraform version `v0.12.12`. After upgrading to `v0.12.31` as suggested in https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570, I was able to download the provider. 

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "sumologic" (terraform-providers/sumologic) 2.9.3...


Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to SumoLogic/sumologic. Please update your source in required_providers.


Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
~/gi/v/terraform/field ➜ ~/Downloads/terraform --version
Terraform v0.12.31
+ provider.sumologic v2.9.3
```

@EdisonHEXUAN @aclarknexient you may want to upgrade to `v0.12.31` to resolve the issue. @denis-matchenko you can upgrade to `v0.11.15`. You can also try pinning the provider version. That might resolve the issue as well if you don't want to upgrade terraform version. See the following section for more details https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570#what-should-i-do-as-a-terraform-0x-user

**Comment by aclarknexient** [comment]
sumovishal thank you very much, your work is deeply appreciated!

**Comment by soleares** [comment]
@sumovishal Thank you! Upgrading to 0.12.31 resolved it for us. Pinning the provider version did not.

**Comment by sumovishal** [comment]
>@sumovishal Thank you! Upgrading to 0.12.31 resolved it for us. Pinning the provider version did not.

Good to know.
