### ISSUE TITLE
sumologic_http_source filters and host_name aren't documented

### ISSUE THREAD

**Issue by mmrobins** [SumoLogic/terraform-provider-sumologic#19]
I would expect the documentation here https://www.terraform.io/docs/providers/sumologic/r/http_source.html to meantion `host_name` and `filter` arguments.  I only know they exist because I imported an existing resource

```
resource "sumologic_http_source" "http_source" {
  name         = var.sumologic_source_name
  category     = var.sumologic_source_category
  collector_id = data.sumologic_collector.collector.id
  description  = var.app_name
  host_name    = var.host_name
  filters {
    filter_type = "Mask"
    mask        = "[FILTERED]"
    name        = "Mask router log"
    regexp      = "path=\"\\/api\\/v1\\/(.*)\""
}
```

**Comment by brianabston001** [comment]
@mmrobins How would it look like if you needed to apply more than one filter? For example multi excludes?

**Comment by seansain** [comment]
Hey, thanks for raising this issue! We have the documentation for the common properties documented [here](https://github.com/terraform-providers/terraform-provider-sumologic/tree/master/website#common-source-properties).

We are working to add it to the docs as well.
