### ISSUE TITLE
Kinesis Firehose for Logs source support

### ISSUE THREAD

**Issue by casey-robertson-hr** [SumoLogic/terraform-provider-sumologic#192]
Would like to request support for the Kinesis Firehose for Logs source:  https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/Amazon-Web-Services/AWS_Kinesis_Firehose_for_Logs_Source

Currently we have to create this in the console to be a source for Kinesis firehose log shipping (shipping AWS WAF v2 logs).  Thanks!

**Comment by vsinghal13** [comment]
Hi @casey-robertson-hr, 

I believe we can define Kinesis Firehose Logs Source in the below format:

```
resource "sumologic_http_source" "kinesisLog" {
	name = "demo-name"
	description = demo-desc"
	category = "demo-desc"
	content_type = "KinesisLog"
	collector_id = "${sumologic_collector.test.id}"
}
```
Will create a task to update the docs to reflect the same. Please try this and confirm if it works for you.

**Comment by vsinghal13** [comment]
cc @Gourav2906

**Comment by Gourav2906** [comment]
I will update docs shortly

**Comment by casey-robertson-hr** [comment]
> I will update docs shortly

Much appreciated, thank you!

**Comment by casey-robertson-hr** [comment]
I tested this out and implemented via Terraform.  It's working great .. thank you!
