### ISSUE TITLE
Failed changes incorrectly showing successful

### ISSUE THREAD

**Issue by ines-upstart** [SumoLogic/terraform-provider-sumologic#204]
Hello, I ran into this issue where applying changes to a resource gave me a green success message, but the changes are not actually made because they were failing behind the scenes.

For example, say that I had a query like:
`_source=example | fields time, user`

and I made a change like:
`_source=example | %"error.message" as msg | fields time, user, msg`

`terraform apply` would give me a success message, but when I checked my query in the UI, the changes were not there. It took some investigation into Sumo's api to get the real error (in this case, it did not like the manual parsing).

**Comment by seansain** [comment]
Thanks for the feedback. We will look into this.

**Comment by nikkehsolaris** [comment]
Hey Sean, would you mind keeping our TAM (TJ V.) tagged in on updates?
