### ISSUE TITLE
Error in connection documentation

### ISSUE THREAD

**Issue by rgooler** [SumoLogic/terraform-provider-sumologic#221]
https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/connection

The documentation says:

`type - (Required) Type of connection. Only WebhookDefinition is implemented right now.`

However, `WebhookDefinition` is wrong, and it should be `WebhookConnection` as the code example shows.

**Comment by casey-robertson-hr** [comment]
Duplicate of https://github.com/SumoLogic/terraform-provider-sumologic/issues/121
