### ISSUE TITLE
Missing documentation for few data sources.

### ISSUE THREAD

**Issue by brewkode** [SumoLogic/terraform-provider-sumologic#242]
Hi folks,

On the https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs page, we don't see some of the data sources. For ex: I was looking for http_source data sources and found it in the repo, however there's no doc for it in the link above. Tried using the data block and it seemed to work. 

I'm wondering if those data sources are not supported or is there a documentation generation related gap. 

PS: Tried searching for similar issues couldn't find any. so, if this is repetitive, please refer to the original issue and close this.

**Comment by sumovishal** [comment]
https://github.com/SumoLogic/terraform-provider-sumologic/pull/251
