### ISSUE TITLE
Please add region support for sumologic_elb_source in authentication section

### ISSUE THREAD

**Issue by ddai1** [SumoLogic/terraform-provider-sumologic#268]
Issue:

I have got following error when creating an elb source for **AWS China**. The AWS credential is valid and I can create a workable source in the SumoLogic console.

Error: { "status" : 400, "id" : "******", "code" : "collectors.validation.fields.invalid", "message" : "Cannot authenticate with AWS." }
with sumologic_elb_source.alb_logs_elb_source
on main.tf line 243, in resource "sumologic_elb_source" "alb_logs_elb_source":

Since **AWS China** has a different api endpoint vs **AWS global**,  the only different between my manually creation vs. terraform creation is I didn't found the argument for specifying the region in the terraform file. My guess is the SumoLogic defaults to the us endpoint if there is no region has been specified.
![sumo_create_alb_source](https://user-images.githubusercontent.com/11204889/132636369-eccaeeb5-eb67-453a-84a6-c1d620a71c9e.png)

With that said, I have done a research, and finally confirmed the region is not supported in your SumoLogic provider. Below is the related code I have highlighted.
https://github.com/SumoLogic/terraform-provider-sumologic/blob/3156c6042e7a9f7d4b8475833329c074d6f3fe5b/sumologic/resource_sumologic_metadata_source.go#L224-L229

**Comment by vsinghal13** [comment]
Thanks @ddai1 for reporting the issue. We will work on adding the same shortly.

**Comment by mccartney** [comment]
Should it be closed now after #277? @vsinghal13
