### ISSUE TITLE
CSE Import: Rule Tuning - rule mappings

### ISSUE THREAD

**Issue by upstart-swiss** [SumoLogic/terraform-provider-sumologic#350]
When importing rule tunings, the rule ids associated with it are not imported

**Comment by pwardecki-sumo** [comment]
It's fixed in the latest version: https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/CHANGELOG.md#2282-february-1-2024

**Comment by pwardecki-sumo** [comment]
@upstart-swiss @simpson-ross 
Closing the issue, feel free to reopen if you face ruleIds problems when importing the Rule Tuning Expressions.
