### ISSUE TITLE
Resource sumologic_kinesis_log_source requires optional field

### ISSUE THREAD

**Issue by eambrosyupgrade** [SumoLogic/terraform-provider-sumologic#361]
### Terraform Version

```
Terraform v0.14.9
+ provider registry.terraform.io/sumologic/sumologic v2.14.0
```

### Affected Resource(s)

- sumologic_kinesis_log_source

### Terraform Configuration Files

Created a module which does not require a path input, and attempted to call it.

```hcl
resource "sumologic_kinesis_log_source" "kinesis_log_source" {
  name         = var.name
  description  = var.description
  category     = var.category
  content_type = var.content_type
  collector_id = var.collector_id
  host_name    = var.host_name
  fields       = local.fields
  timezone     = var.timezone

  dynamic "authentication" {
    for_each = var.authentication
    content {
      type     = "AWSRoleBasedAuthentication"
      role_arn = authentication.value["role_arn"]
    }
  }
  dynamic "path" {
    for_each = var.path
    content {
      type            = path.value["type"]
      bucket_name     = path.value["bucket_name"]
      path_expression = path.value["path_expression"]
      scan_interval   = path.value["scan_interval"]
    }
  }
}

module "my_actual_kinesis_source" {
  source       = "../../modules/kinesis_log_source"
  name         = "My actual source"
  category     = "my/categor"
  content_type = "KinesisLog"
  host_name    = "hostname"
  collector_id = my_collector.id
}
```

### Debug Output

```
Error: [ERROR] no path specification in kinesis log Soruce

  on ../../modules/kinesis_log_source/main.tf line 6, in resource "sumologic_kinesis_log_source" "kinesis_log_source":
   6: resource "sumologic_kinesis_log_source" "kinesis_log_source" {
```

### Expected Behavior

I should have been able to apply on an already existing resource, since this is not a required field.

### Actual Behavior

The Sumo provider errors on any Path length that's 0. Making this field not optional in the provider. See [this func](https://github.com/SumoLogic/terraform-provider-sumologic/blob/4f01a239d192dd5fff48a5787ff6537f97e55102/sumologic/resource_sumologic_kinesis_log_source.go#L198-L220)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

My kinesis sources already exist in sumologic, importing them into terraform I can see in the state that the path is blank `"path": [],` 

### References

- [Function causing error](https://github.com/SumoLogic/terraform-provider-sumologic/blob/4f01a239d192dd5fff48a5787ff6537f97e55102/sumologic/resource_sumologic_kinesis_log_source.go#L198-L220)
- [Authentication func with no else statement](https://github.com/SumoLogic/terraform-provider-sumologic/blob/4f01a239d192dd5fff48a5787ff6537f97e55102/sumologic/resource_sumologic_kinesis_log_source.go#L222-L252)
- Documentation on the Kinesis Log Source resource list the [path block as optional](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/kinesis_log_source#path).

**Comment by davidnortonjr-sps** [comment]
We see the same thing. And when we specify 

```
  path {
    type = "NoPathExpression"
  }
```

, then the resource perpetually shows a change that it wants to apply:

```
  ~ resource "sumologic_kinesis_log_source" "audit" {
        id                           = "redacted"
        name                         = "redacted"
        # (11 unchanged attributes hidden)

      + path {
          + scan_interval = 300000
          + type          = "NoPathExpression"
        }

        # (1 unchanged block hidden)
    }
```
