### ISSUE TITLE
SUMOLOGIC_ACCESSID and SUMOLOGIC_ACCESSKEY aren't picked up from the environment during provider initialization

### ISSUE THREAD

**Issue by roshbhatia** [SumoLogic/terraform-provider-sumologic#364]
**steps to reproduce**
1. Have variables exported in the environment.
2. Follow environment variable authentication strategy found in https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs.
4. Run `init`/`plan` and watch it error.

**relevant info**
In required providers:
```
  sumologic = {
    source  = "sumologic/sumologic"
    version = ">= 2.11.4"
  }
```

**Comment by sumovishal** [comment]
@roshbhatia I am unable to reproduce this. Can you provide more details? Can you share all the env variables you exported and the error you get on terraform init?
