### ISSUE TITLE
Feature Request: scheduled searches & alert support

### ISSUE THREAD

**Issue by flopmeister** [SumoLogic/terraform-provider-sumologic#40]
Are there any plans to add a dedicated resource for scheduled searches & alerts based on those searches in the future?

In the meantime, is it possible to leverage `scheduled_views` for similar purposes?

**Comment by shris-github** [comment]
@flopmeister Yes, we have plans to extend support for Alerting in our Terraform provider. We are coming out with a few alerting features in the next couple of months and will also have a TF resource for the same.

**Comment by mccartney** [comment]
@flopmeister 
Meanwhile you can use the `sumologic_content` resource for scheduled searches.

`scheduled_views` are supported too, but they are a different notion in Sumo Logic. In short - they are a way to pre-aggregate (or pre-process) some log information when it's being accepted into Sumo Logic. See https://help.sumologic.com/Manage/Scheduled-Views

**Comment by mgraczykowski** [comment]
Apart from `scheduled searches` & `alerts`, we're also working on a dedicated resource for metrics alert monitors.

**Comment by rsanbhad** [comment]
@flopmeister We announced the general availability of our new [alerting](https://help.sumologic.com/?cid=10020) resources last week - they are available under the `sumologic_monitor` resource for logs and metrics monitors. I'll close this issue based on that - feel free to give it a try and let us know any feedback you have!
