### ISSUE TITLE
sumologic_http_source timezone attribute

### ISSUE THREAD

**Issue by jrobison-sb** [SumoLogic/terraform-provider-sumologic#408]
When upgrading from 2.16.2 to 2.17.0, I noticed this in my Terraform plan diffs:
```
~ resource "sumologic_http_source" "ecs" {
      - timezone                     = "Etc/UTC" -> null
        # (11 unchanged attributes hidden)
    }
```

I see in https://github.com/SumoLogic/terraform-provider-sumologic/pull/392 that timezone is now considered optional, which explains why I would get such a diff (I hadn't previously specified any value for timezone). And if I add an attribute for timezone I can make this diff resolve itself, so it does indeed seem like a valid (optional) attribute.

But AFAICT timezone isn't documented anywhere as being optional. I would expect it to be documented [here](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/http_source), but it isn't. If this attribute is indeed valid, should it be documented in the docs for the resources which support it?

**Comment by dlinsumo** [comment]
Internal ticket SUMO-198408

**Comment by kevin-sumo** [comment]
"timezone" is a common Source property used by all source types and is currently documented under the [Common Source Properties](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs#common-source-properties) linked under the Argument Reference section of each Source type.

**Comment by prowlaiii** [comment]
We've just started getting this in a number of Terraform stacks.
The question is do we need to 
1. update all of our calls to sumologic_http_source to specify the timezone attribute, or
2. null means Etc/UTC?
It's quite pressing to get an answer to this, as we have updates to apply.

**Comment by kevin-sumo** [comment]
1.) The timezone attribute should be optional. 
2.) When Null is set within the timezone attribute of the Source, then the timezone applied to data from this Source is inherited from the timezone set at the Collector, which by default is set to Etc/UTC.

**Comment by prowlaiii** [comment]
Thanks for the info; however, this change to the default has a blast-radius.
