### ISSUE TITLE
SLO Queries List

### ISSUE THREAD

**Issue by jshlbrd** [SumoLogic/terraform-provider-sumologic#421]
This is either a mistake in documentation or a bug in the provider, but how can I provide multiple queries for a single metrics SLO? [This example](https://github.com/SumoLogic/terraform-provider-sumologic/blob/2d8f1058dbf6cb21d7abc1b4213303f87424d03d/website/docs/r/slo.html.markdown#example-slo) only shows one query, but SLOs created in the UI can have many queries.

**Comment by dlinsumo** [comment]
SUMO-200350

**Comment by apoorv-garg** [comment]
@jshlbrd PR to improve the docs https://github.com/SumoLogic/terraform-provider-sumologic/pull/422

This has an example for multiple queries in single SLO (aka ratio based definition)

**Comment by jshlbrd** [comment]
thanks @apoorv-garg, that explains things! separate question: why are the time periods in the Terraform provider different than the UI? Week, Month, and Quarter also don't seem to be valid options because they cause errors.

`expected compliance.0.size to be one of [Week Month Quarter 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d]`

**Comment by apoorv-garg** [comment]
> Week, Month, and Quarter also don't seem to be valid options because they cause errors.

can you please share your config ?

**Comment by apoorv-garg** [comment]
> why are the time periods in the Terraform provider different than the UI
I assume you are referring to the fact that you are not able to configure something like `30d`. Thanks for reporting this, will fix it shortly. This is an artefact of duplicating validations both in the provider and in the sumo backend - benefit is you get early feedback (`terraform validate` time as opposed to `terraform plan`) but downside is drift in the validations (we relaxed the validation in sumo backend, but forgot to update here, sorry!)

**Comment by jshlbrd** [comment]
thanks @apoorv-garg! regarding use of Week, Month, Quarter, here's an example configuration:
```
  compliance {
    compliance_type = "Rolling"
    size            = "Month"
    target          = 90
    timezone        = "Etc/UTC"
  }
```

it produces this error:
```
│ Error: {"id":"WQLOO-4U7C8-OD58O","errors":[{"code":"slos:invalid_slo_compliance","message":"Invalid SLO compliance.","detail":"Rolling compliance duration: 'Month' is not a valid time range format. Example: 7d"}]}
```

if you change it to "1Month", then it returns the compliance size error discussed earlier.

**Comment by apoorv-garg** [comment]
`Month` `Week` and `Quarter` are supposed to be used only when `compliance_type` is `Calendar`.

When `compliance_type` is `Rolling`, you can use `1d` `2d` ... and so on. (The provider will error out after `14d` right now, which is the bug I've fixed above. once that fix is released, you can configure up to `90d` rolling periods)

**Comment by apoorv-garg** [comment]
FYI: the provider version with the above fix has been released https://registry.terraform.io/providers/SumoLogic/sumologic/2.18.1
