### ISSUE TITLE
The provider provider.sumologic does not support resource type "sumologic_s3_source".

### ISSUE THREAD

**Issue by snappydragon1** [SumoLogic/terraform-provider-sumologic#431]
Sumo provider version is 2.1.2

I get this error  **The provider provider.sumologic does not support resource type "sumologic_s3_source".** for the resource sumologic_s3_source

**sumologic_s3_source configuration**
resource "sumologic_s3_source" "member_rewards_s3_sumologic" {
  name          = "Amazon S3 Source"
  description   = "My description"
  category      = "aws/s3"
  content_type  = "AwsS3Bucket"
  scan_interval = 300000
  paused        = false
  collector_id  = "${sumologic_collector.collector.id}"

  authentication {
    type = "AWSRoleBasedAuthentication"
    role_arn = "smear"
  }

  path {
    type = "S3BucketPathExpression"
    bucket_name     = "somebucketname"
    path_expression = "somepath"
  }
}

Please let me know f I am missing any configuration.

**Comment by dlinsumo** [comment]
Internal JIRA SUMO-202103

**Comment by kevin-sumo** [comment]
Support for the"sumologic_s3_source" resources was added in [v2.2.0](https://github.com/SumoLogic/terraform-provider-sumologic/releases/tag/v2.2.0) of the provider. You will need to upgrade to use this provider version, or later, to take advantage of this resources type.

**Comment by snappydragon1** [comment]
Thanks. It works :)
