### ISSUE TITLE
Add suppression for equivalent time values in JSONs in sumologic_content

### ISSUE THREAD

**Issue by MZochowskiSUMO** [SumoLogic/terraform-provider-sumologic#444]
Time values can be written in many equivalent formats, e.g.: 3600s = 60m = 1h. All of the are acceptable, but only one will be returned by SUMO API call done by Terraform to refresh state. As a result, if the resource defined in `.tf` file has some time value written in non-canonical form it will be always present in `terraform plan` outputs. This is already done for other resources in https://github.com/SumoLogic/terraform-provider-sumologic/pull/442, only JSON backed `sumologic_content` remains.

## Steps to reproduce

1. Create dashboard using sumologic_content:
**main.tf:**
```
resource "sumologic_content" "tf_dashboards_test_to_be_removed_idempotency" {
  parent_id = "0942345772637BFD"
  config = templatefile("dashboards/dashboard.json", {})
}
```
**dashboards/dashboard.json:**
```
{
    "type": "DashboardV2SyncDefinition",
    "name": "Dashboard Sep 30, 2022 05:27:30",
    "description": "",
    "title": "Dashboard Sep 30, 2022 05:27:30",
    "theme": "Light",
    "topologyLabelMap": {
        "data": {}
    },
    "refreshInterval": 0,
    "timeRange": {
        "type": "BeginBoundedTimeRange",
        "from": {
            "type": "RelativeTimeRangeBoundary",
            "relativeTime": "-60m"
        },
        "to": null
    },
    "coloringRules": [],
    "layout": {
        "layoutStructures": [],
        "layoutType": "Grid"
    },
    "panels": [],
    "variables": []
}
```
2. `terraform apply`

## Observed result

After the next `terraform apply` we still see the change from `-1h` to `-60m` in computed plan.

## Expected result

Such diffs should be ignored. The plan after the next `terraform apply` should be empty.

**Comment by dlinsumo** [comment]
Sumo internal SUMO-203420

**Comment by dlinsumo** [comment]
We are moving away from the Content Management APIs and towards native TF CRUD support.  As such, we are not prioritizing enhancements to Content Management APIs.
