### ISSUE TITLE
[sumologic_http_source] Not able to set Service Name and other properties for `Rum` HTTP source

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/terraform-provider-sumologic#468]
Version: 2.20.0

When creating an HTTP source of type [Rum](https://help.sumologic.com/docs/apm/real-user-monitoring/#step-1-create-a-rum-http-traces-source) with Terraform, I don't seem to be able to specify the "Advanced options for Browser RUM" as described in the UI:

- Application Name
- Service Name
- Probabilistic sampling rate
- Ignore urls
- Custom Tags
- Propagate Trace Header Cors Urls
- Geolocation recognition

![image](https://user-images.githubusercontent.com/70892616/211757873-2485a1a9-f6f9-4828-915c-99ba61daeacb.png)

I'm using the following code in Terraform, similar to what's described in the [docs](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/http_source):

```tf
resource "sumologic_http_source" "http_rum_source" {
  name = "HTTP RUM"
  description = "My description"
  category = "my/source/category"
  content_type = "Rum"
  collector_id = "${sumologic_collector.test.id}"
}

resource "sumologic_collector" "collector" {
  name        = "my-collector"
  description = "Just testing this"
}
```

**Comment by vsinghal13** [comment]
Will need to add new parameters for this.
sample `thirdpartyRef`:
```
thirdPartyRef
: 
"{\"resources\":[{\"serviceType\":\"Rum\",\"path\":{\"type\":\"RumPath\",\"serviceName\":\"test-rum\",\"samplingRate\":1.0,\"ignoreUrls\":[],\"customTags\":{},\"propagateTraceHeaderCorsUrls\":[]},\"authentication\":{\"type\":\"NoAuthentication\"}}]}

```

**Comment by vsinghal13** [comment]
solved by https://github.com/SumoLogic/terraform-provider-sumologic/pull/547
