### ISSUE TITLE
Support Data source for Folders apart from Personal_folder

### ISSUE THREAD

**Issue by AshutoshNirkhe** [SumoLogic/terraform-provider-sumologic#48]
Currently I see 'sumologic_personal_folder' data source can get you the ID for personal folder and I can pass that as parent id while creating any scheduled search. But it will be useful if we could find ID for any Folder (not just personal folder).
Are you planning to support Data source say 'sumologic_folder' as a generic one to get ID for any folder we pass ?
Otherwise, we have no option but to use Sumologic's REST API to get the ID for the folder first and then pass it while creating scheduled search, which is really not ideal.

**Comment by mgraczykowski** [comment]
[`sumologic_folder`](https://www.terraform.io/docs/providers/sumologic/r/folder.html) resource exports attribute `id`, so you can define a folder hierarchy directly in terraform:

```
data "sumologic_personal_folder" "personalFolder" {}

resource "sumologic_folder" "parent_folder" {
  name        = "Parent Folder"
  parent_id   = "${data.sumologic_personal_folder.personalFolder.id}"
}

resource "sumologic_folder" "child_folder" {
  name        = "Child Folder"
  parent_id   = sumologic_folder.parent_folder.id
}
```

To manage already existing folders in this way you either need to re-create the folders in terraform or add them manually to the terraform state with [`terraform import`](https://www.terraform.io/docs/import/index.html) command.

Is this helpful in your case?

**Comment by AshutoshNirkhe** [comment]
Thanks Michal for the answer. It heps me partially I think.

What if we have a parent folder which is not under any Personal Folder ?
E.g -
My folder hierarchy is say -
Organization
  -> Department
     -> Product
       -> ScheduledSearches 

In this case how we can get the ID for topmost parent folder i.e. 'Organization' ?

**Comment by mgraczykowski** [comment]
As far as I know, unfortunately at the moment you would need to obtain `id` of the topmost parent folder manually (so via API or in the UI) and then use it as a constant in terraform. Let me follow up with the team on plans around this experience.

**Comment by AshutoshNirkhe** [comment]
Ok thanks for the information. 
Please let me know once you hear back from the team. Thank you!

**Comment by djsly** [comment]
@AshutoshNirkhe we should be able to maybe use a static ID. 

@mgraczykowski  you guys should look at supporting a data source for https://www.terraform.io/docs/providers/sumologic/r/folder.html

right now there is only a data source for personal folder.

**Comment by sumovishal** [comment]
> @mgraczykowski you guys should look at supporting a data source for [terraform.io/docs/providers/sumologic/r/folder.html](https://www.terraform.io/docs/providers/sumologic/r/folder.html)

We will look into that.

**Comment by eambrosyupgrade** [comment]
Circling back on this old (and seemingly abandoned) issue, without the ability to grab other folder IDs it isn't clear how one would import existing content or folders that are under the global folder (or other personal folders) into tf.

**Comment by mgraczykowski** [comment]
Pinged our terraform team about the issue

**Comment by sumovishal** [comment]
@eambrosyupgrade it's on our list of things to do. We plan to pick it up in the next month.
