### ISSUE TITLE
Missing 2.20.1 release?

### ISSUE THREAD

**Issue by hybby** [SumoLogic/terraform-provider-sumologic#491]
Referencing version 2.20.1 (or ~> 2.20.0) seems to fail with:

```
 │ Error: Failed to install provider
 │ 
 │ Error while installing sumologic/sumologic v2.20.1: could not query
 │ provider registry for registry.terraform.io/sumologic/sumologic: failed to
 │ retrieve authentication checksums for provider: 404 Not Found returned from
 │ github.com
```

```
terraform {
  required_providers {
    sumologic = {
      source = "SumoLogic/sumologic"
      version = "2.20.1"
    }
  }
}
```

Could this be that there is no Release published for v2.20.1?

https://github.com/SumoLogic/terraform-provider-sumologic/releases

I see that the tag exists, as does the mention on the registry:

* https://github.com/SumoLogic/terraform-provider-sumologic/tree/v2.20.1
* https://registry.terraform.io/providers/SumoLogic/sumologic/2.20.1

**Comment by dlinsumo** [comment]
We previously released 2.20.1 incorrectly and had since rolled back.  Please use the latest 2.21.0.
