### ISSUE TITLE
sumologic_role - capabilities order triggers changes

### ISSUE THREAD

**Issue by seansain** [SumoLogic/terraform-provider-sumologic#55]
Looks like the list of capabilities is position dependent and thus is triggering changes if not specified in specific order:
```
  # sumologic_role.developers will be updated in-place
  ~ resource "sumologic_role" "developers" {
      ~ capabilities     = [
            "manageFieldExtractionRules",
            "manageConnections",
          - "manageMonitors",
            "viewCollectors",
          + "manageMonitors",
        ]
        id               = "000000000021AC0F"
        name             = "Developers"
    }
```
- Transferred from old repo ~@ Constantin07

**Comment by msuterski** [comment]
+1

Managing roles through terraform triggers changes to roles even if their capabilities did not change. 

I was also not able to find what the other of all capabilities is on Sumo Logic documentation.

**Comment by peikk0** [comment]
Same thing with role IDs for users. Those parameters should be using a set instead of a list.
