### ISSUE TITLE
sumologic_app not functioning, error codes not helpful

### ISSUE THREAD

**Issue by H3llscr3am** [SumoLogic/terraform-provider-sumologic#680]
when attempting to utilize Terraform to install applications on our instance, it doesn't work even though it appears to be generally available through the documentation.

https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/app

every attempt that we've tried has lead to Error: async job failed - {integrations:api_errors Multiple errors occurred while installing app with uuid=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX...

according to support this might be because our service account is controlled through SAML, but the same account is fully capable of performing all the other terraform provider actions we're using. 

We've tried installing multiple applications.
We've tried defining the version as latest and manually as the current version listed in the app store.
When we perform the application installation through API it works fine using the same account/credentials.

**Comment by dlinsumo** [comment]
Filed internal ticket SUMO-246859

**Comment by dlinsumo** [comment]
Hi, I believe team had already worked with you to fix the TF SAML issue.  Just want to check if you are still facing the app install errors?
