### ISSUE TITLE
Sumologic monitor folder fails silently

### ISSUE THREAD

**Issue by blame19** [SumoLogic/terraform-provider-sumologic#80]
Having issues while trying the new monitor_folder and metrics_monitor resources as documented here:[https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/monitor](url) with sumologic provider version 2.2.1

Trying to instantiate a metric monitor fails, giving out non clear errors in the terraform apply.
I tested both creating a new monitor_folder and then a metric monitor, like in the docs:
```
`resource "sumologic_monitor_folder" "monitor_folder" {
  name        = "${var.folder_name}-monitors"
  description = var.folder_description
}

resource "sumologic_monitor" "metrics_monitor" {
  for_each = var.monitor_configs

  parent_id    = sumologic_monitor_folder.monitor_folder.id
  name         = format("%s", each.key)
  description  = each.value.description
  type         = "MonitorsLibraryMonitor"
  is_disabled  = false
  content_type = "Monitor"
  monitor_type = "Metrics"
  queries {
    row_id = "A"
    query  = each.value.query
  }
  triggers {
    threshold_type   = each.value.triggers.threshold_type
    threshold        = each.value.triggers.threshold
    time_range       = each.value.triggers.time_range
    occurrence_type  = each.value.triggers.occurrence_type
    trigger_source   = "AllTimeSeries"
    trigger_type     = "ResolvedCritical"
    detection_method = "StaticCondition"
  }
  notifications {
    notification {
      action_type  = "EmailAction"
      recipients   = each.value.email_notification_list
      subject      = "Triggered: ${format("%s", each.key)}"
      time_zone    = "PST"
      message_body = ""
    }
    run_for_trigger_types = ["Critical", "ResolvedCritical"]
  }
}`
```

And by giving the id of an already existing personal folder to the metric monitor:

```
`resource "sumologic_monitor" "metrics_monitor" {
  for_each = var.monitor_configs

  parent_id    = data.sumologic_personal_folder.personalFolder.id
  name         = format("%s", each.key)
  description  = each.value.description`
```
In both cases, the apply fails without giving a reason:

```
Error: {"id":"V3PXX-408CZ-TQHAA","errors":[]}
  on .terraform/modules/xinfra-ci-aks-dev.sumologic-kubernetes-cluster-configurations/sumologic-content.tf line 69, in resource "sumologic_monitor_folder" "monitor_folder":
  69: resource "sumologic_monitor_folder" "monitor_folder" {
```

```
`Error: {"id":"P86EV-M4HY2-MDG42","errors":[]}
  on .terraform/modules/matteo-aks-dev.sumologic-kubernetes-cluster-configurations/sumologic-content.tf line 75, in resource "sumologic_monitor" "metrics_monitor":
  75: resource "sumologic_monitor" "metrics_monitor" {`
```

It's also worth noting that the online docs lacks a section about the sumologic_monitor_folder, that might be part of the issue, as I get the impression that a monitor folder is needed in order to deploy metrics monitors correctly.

**Comment by rsanbhad** [comment]
Hey @blame19 ,

Our new Monitors feature is currently in closed Beta (https://help.sumologic.com/Beta/Monitors) - the error you're getting means that your account doesn't have access to this feature, only accounts enrolled in the Beta have the necessary permissions enabled. We'll update the docs to make this more clear - thanks for pointing this out. Also as you pointed out, the error message should have been clearer about what the nature of the problem was - I'm not entirely sure why it didn't, I'll raise a ticket internally to look into that.

**Comment by djsly** [comment]
Rohit, we want to create metric monitors. We have them in the UI already. 

How can we move forward with managing our metric based monitors ? 

We have the new metrics Beta feature enabled already.

**Comment by angadrandhawa** [comment]
Hey Blame, 

The capability exposed to the Terraform is different from the Metrics Monitor's capability. Long story short, we at Sumo are working on new unified alerting mechanism across logs and metrics. This feature is in beta currently. 

If you are interested in learning more about this feature, then please contact or AE or SE or email us at alerting-beta [at] sumologic [dot] com. We can provide more details there.

**Comment by djsly** [comment]
How can we create metric monitors with terraform then ?

**Comment by tarunk2** [comment]
@djsly I just stumbled upon this issue. Were you able to configure monitors using Terraform?

**Comment by djsly** [comment]
Not sure we could.  We moved away from sumologic so we haven’t needed that feature in the end.

**Comment by tarunk2** [comment]
We are able to create a monitor folder and metrics monitor via terraform so closing this issue.
