### ISSUE TITLE
Remove vendor dir

### ISSUE THREAD

**Issue by pmalek-sumo** [SumoLogic/terraform-provider-sumologic#84]
Given that officially supported go version is `>= 1.13` I gather `vendor/` dir can be safely removed.

**Comment by seansain** [comment]
The vendor directory is used by our CI so that it does not have to download all the packages when it runs tests.

**Comment by pmalek-sumo** [comment]
Alright, fair point. In shouldn't make that big of a difference though anyway (unless I'm proven otherwise 🤷🏻‍♂️  :) )
