### ISSUE TITLE
Bug: plan for sumologic_field_extraction_rule *always* has update in-place diff on `parse_expression`

### ISSUE THREAD

**Issue by gkop** [SumoLogic/terraform-provider-sumologic#89]
First, thanks for the helpful provider! :)

Even though we don't change the resource definition of our `sumologic_field_extraction_rule`, on 100% of our terraform plans we see a diff. The diff reports an update in-place on the `parse_expression` configuration argument. I have manually diffed to confirm that the argument reported by the plan is exactly the same every time.

While this has yet to cause us functional problems on the Sumo side, it breaks the Terraform abstraction, and creates noise in our plans, making them challenging to read. Also, within the Sumo web UI, the Last Modified time is updated for the Field Extraction Rule _every time_ we do a Terraform apply, even though we haven't made any changes, which is confusing and means it cannot be relied upon.

I found this behavior on version 2.3.0 of the provider (as well as various versions going back at least to 2.1.1), with Terraform 0.12.

**Comment by seansain** [comment]
Hi, I'm glad you find the provider helpful! Thanks for submitting this issue. I understand your concerns, however, I am not able to reproduce the issue. Could you provide some more information as to your terraform configuration, especially the `parse_expression` you are using? Thank you!

**Comment by gkop** [comment]
Thanks for the quick response Sean! May I email you? Send a message at gkopley@mulesoft.com

**Comment by seansain** [comment]
Sure, I'll follow up on email.
