### ISSUE TITLE
Feature request: Local File Source support

### ISSUE THREAD

**Issue by Philipp-Navis** [SumoLogic/terraform-provider-sumologic#90]
Hi,

it would be great if this Terraform provider could add the support for adding Local File sources as documented here: 
https://help.sumologic.com/03Send-Data/Sources/01Sources-for-Installed-Collectors/Local-File-Source

Thanks,
Philipp

**Comment by vsinghal13** [comment]
resource added in  https://github.com/SumoLogic/terraform-provider-sumologic/issues/90
